spring.application.name=Order_Spring_DesignPatterns

spring.jpa.show-sql=true

### propriedade que pega o valor da variável de ambiente; caso não seja encontrado, o valor é "my-secret-key"
api.security.token.secret=${JWT_SECURITY:my-secret-key}