spring.application.name=Order_Spring_DesignPatterns

spring.jpa.show-sql=true

# Desabilita diferenciação entre maiúsculas e minúsculas para enums durante mapeamentos JSON
spring.jackson.mapper.accept-case-insensitive-enums=true

# Configurações LLM - Google GenAI: token, modelo de chat e variação na resposta
spring.ai.google.genai.api-key=${TOKEN_API_GOOGLE_GENAI}
spring.ai.google.genai.chat.model=gemini-3.6-flash
spring.ai.google.genai.chat.temperature=0.6

# Configurações SST - Groq/OpenAI: token, modelo de transcription, linguagem do áudio e url para conexão e transcrição
spring.ai.openai.api-key=${TOKEN_API_GROQ_SST}
spring.ai.openai.audio.transcription.model=whisper-large-v3-turbo
spring.ai.openai.audio.transcription.language=pt
spring.ai.openai.audio.transcription.base-url=https://api.groq.com/openai/v1